//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public Actions()
        {
            this.ThingsDones = new HashSet<ThingsDone>();
            this.Reminders = new HashSet<Reminder>();
        }
    
        public int index { get; set; }
        public string Title { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public string IPAddress { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual ICollection<ThingsDone> ThingsDones { get; set; }
        public virtual ActionCategory ActionCategory { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }

        public static implicit operator Actions(List<Actions> v)
        {
            throw new NotImplementedException();
        }
    }
}
