//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public Actions()
        {
            this.ThingsDones = new HashSet<ThingsDone>();
        }
    
        public int index { get; set; }
        public string Title { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
    
        public virtual ICollection<ThingsDone> ThingsDones { get; set; }
        public virtual Actions Actions1 { get; set; }
        public virtual Actions Action1 { get; set; }
        public virtual ActionCategory ActionCategory { get; set; }
    }
}
