//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticThought
    {
        public int index { get; set; }
        public System.DateTime HappenTime { get; set; }
        public bool Delete { get; set; }
        public string Situation { get; set; }
        public Nullable<int> EmotionsRating { get; set; }
        public string AutomaticThought1 { get; set; }
        public Nullable<int> AutomaticThoughtRating { get; set; }
        public string RationalResponThought { get; set; }
        public Nullable<int> RationalResponRating { get; set; }
        public string OurcomeThought { get; set; }
    }
}
