//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Issues { get; set; }
        public string Planned { get; set; }
        public bool Deleted { get; set; }
    }
}
