//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int ID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string WhatHappened { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
