//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidSize
    {
        public LiquidSize()
        {
            this.ThingsDones = new HashSet<ThingsDone>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public bool Deleted { get; set; }
        public string IPAddress { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual LiquidSize LiquidSize1 { get; set; }
        public virtual ICollection<ThingsDone> ThingsDones { get; set; }
    }
}
