//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Autos = new HashSet<Auto>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public string PersonName { get; set; }
    
        public virtual ICollection<Auto> Autos { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
