//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ID { get; set; }
        public bool Deleted { get; set; }
        public string IPAddress { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ActionID { get; set; }
        public int RemeberType { get; set; }
        public int Every { get; set; }
    
        public virtual Actions Action { get; set; }
        public virtual ReminderType ReminderType { get; set; }
    }
}
