//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.Weights = new HashSet<Weight>();
        }
    
        public int SizeID { get; set; }
        public int PeopleID { get; set; }
        public Nullable<int> Wrist { get; set; }
        public Nullable<int> Chest { get; set; }
        public Nullable<int> Forearm { get; set; }
        public Nullable<int> Waist { get; set; }
        public Nullable<int> Thigh { get; set; }
        public Nullable<int> Hip { get; set; }
        public Nullable<int> Calve { get; set; }
        public Nullable<int> Bicep { get; set; }
        public Nullable<int> Neck { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IPAddress { get; set; }
        public string Broswer { get; set; }
        public System.DateTime StatusDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Weight> Weights { get; set; }
    }
}
