//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Items = new HashSet<Item>();
            this.PriceHistories = new HashSet<PriceHistory>();
        }
    
        public int ID { get; set; }
        public string StoreName { get; set; }
        public string IPAddress { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
    }
}
