//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        [DisplayName("Store Name")]
        public string StoreName { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
