//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNWebApps.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public int WeightID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> Pound { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IPAddress { get; set; }
        public string Broswer { get; set; }
        public System.DateTime StatusDate { get; set; }
    
        public virtual Size Size { get; set; }
    }
}
